### ISSUE TITLE
Opcodes should parse until whitespace, not line end

### ISSUE THREAD

**Issue by stijnfrishert** [andamira/sofiza#2]
The current regex for opcodes is `[a-zA-Z0-9_]+=.+`. Maybe it's better to use something like `[a-zA-Z0-9_]+=[[:word:]]+`?

I ran into an sfz that doesn't load pretty quickly, because it has multiple opcodes on the same line.
This sfz was linked to by sfzformat.com itself.

https://sfzinstruments.github.io/melodic-percussion/mslp_vibes

```
<region>
sample=3_F.wav
lokey=0 hikey=53
pitch_keycenter=53
ampeg_decay=25.0
```

**Comment by joseluis** [comment]
A dot must be included too, in order for the sample filename extension to not be left out.  `[a-zA-Z0-9_]+=[\w.]+` works in this case.

The bigger problem is that if I change the regexp to that, the filenames with spaces are interpreted as separate opcodes. E..g:
`sample=MOHorn mute_A#1_v1_1.wav`

I'm not sure what the best solution is here... Maybe it could be possible to refactor the parser in order to recognize "sample=.*" as a special kind of opcode that can't have any other opcode after it in the same line... and only then check for the more general opcodes...

**Comment by joseluis** [comment]
This should be fixed now. It was way easier than I thought...
